# -*- coding: utf-8 -*-
"""Uber Data Analysis .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jEUopVkFNTVQ33z0-670LeQmg82KdAbX
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
sns.set()

df=pd.read_csv('/content/archive.zip')
df.head()

df.info()

df.columns=['Start_date','End_date','Category',
            'Start_loc','End_loc','Miles','Purpose']

df.isna().sum()

df.isna()

df.isna().sum()

df.Purpose=df.Purpose.replace(to_replace=np.nan,value='Missing_record')

df.isna().sum()

df.dropna(inplace=True)

df.isna().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df.duplicated().sum()

df.Purpose.value_counts()

df.Category.value_counts()

df.info()

df['Start_date'] = pd.to_datetime(df['Start_date'])

df['End_date'] = pd.to_datetime(df['End_date'])

df.info()

df['Month']=df['End_date'].dt.month_name()

df['Day']=df['End_date'].dt.day_name()

df.sample(3)

pivot_Day =pd.pivot_table(data=df,index='Day',values='Category',aggfunc='count')
pivot_Day

pivot_Day.plot.bar()

pivot_Month =pd.pivot_table(data=df,index='Month',values='Category',aggfunc='count')
pivot_Month

pivot_Month.plot.barh()

df['Miles'].describe()

df.boxplot()

sns.boxplot(y="Miles",data=df)

sns.boxplot(x="Miles",y="Day",data=df)

value_category =df['Category'].value_counts().to_frame().reset_index()
value_category

sns.countplot(x='index',data=value_category)

Purpose_mails = df.groupby('Purpose').mean()
Purpose_mails

Purpose_mails.plot.barh()

Pur_mails=Purpose_mails.reset_index()
Pur_mails

plt.barh(Pur_mails['Purpose'],Pur_mails['Miles'])
plt.title('Purpose by mean of mails')
plt.xlabel('mean of mails')
plt.ylabel('Purpose')
plt.figure(figsize=(20,10))
plt.show()